### ISSUE TITLE
Individual (package private) test method execution stomps snapshot state from other methods

### ISSUE THREAD

**Issue by iaincd** [diffplug/selfie#174]
I’m finding that if I:

1. Have a `FooTests.java` with multiple selfie-taking test methods
2. Successfully generate `FooTests.ss`, with labelled sub-snapshots
3. Execute only (e.g.) `fooTest1()` via IntelliJ (using Gradle test runner)

…that this results in `FooTests.ss` being updated to contain _only_ the snapshot state for the individually-executed method, thereafter causing `fooTest2()`, and so on to fail.

Might this be another situation where GC is too aggressive on account of package-private methods?

Side note: Rewriting the `.ss` file at all when there are no control comments or `_TODO()`s in play feels a little confounding in general — might it be worth gating all GC/snapshot writes behind those, or else perhaps the invocation of a `clean` (or other dedicated) task?

**Comment by nedtwigg** [comment]
Fixed in `1.1.2`.

**Comment by iaincd** [comment]
Thanks for another speedy fix!
