### ISSUE TITLE
[Feature Request] Opt-In to write Snapshots to other source roots

### ISSUE THREAD

**Issue by Obirah** [diffplug/selfie#480]
I am using selfie to perform snapshot testing in Spring integration tests for Thymeleaf templates. In order to cleanly organize my test code, I have a separate (`src/integrationTest/kotlin`) source set for my integration tests that start a Spring test app.

When adding this source set to the `otherSourceRoots` value in `SelfieSettings`, selfie works nicely. However, (as intended and documented) selfie does not write Snapshot files to that source set but rather to `src/test/kotlin`.

I would love to see an option that allows to opt-in to writing the snapshots to the source set that the test is located in, so that other developers can easily find snapshots that I store and don't have to look for them in `src/test`.

**Comment by nedtwigg** [comment]
You can override this method (`@Override File getRootFolder()` in java-speak) and set the snapshot folder to be whatever you want.

https://github.com/diffplug/selfie/blob/a88b7a5535f33de6020d433772010ca43b78ace1/jvm/selfie-runner-junit5/src/main/kotlin/com/diffplug/selfie/junit5/SelfieSettingsAPI.kt#L65-L80

Is that enough control? Or do you want to snapshots to be in multiple different source roots?

**Comment by Obirah** [comment]
That's enough for me, thank you for pointing me towards that approach!
